// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: file_storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос регистрации файла → выдаём URL для загрузки
type RegisterFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename    string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                          // исходное имя (можно пустое)
	EntityName  string `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`    // название сущности, к которой файл относится (например, document)
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // например "application/pdf"
}

func (x *RegisterFileRequest) Reset() {
	*x = RegisterFileRequest{}
	mi := &file_file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFileRequest) ProtoMessage() {}

func (x *RegisterFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFileRequest.ProtoReflect.Descriptor instead.
func (*RegisterFileRequest) Descriptor() ([]byte, []int) {
	return file_file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RegisterFileRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *RegisterFileRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type RegisterFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId int32  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	PutUrl string `protobuf:"bytes,2,opt,name=put_url,json=putUrl,proto3" json:"put_url,omitempty"` // presigned PUT
}

func (x *RegisterFileResponse) Reset() {
	*x = RegisterFileResponse{}
	mi := &file_file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFileResponse) ProtoMessage() {}

func (x *RegisterFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFileResponse.ProtoReflect.Descriptor instead.
func (*RegisterFileResponse) Descriptor() ([]byte, []int) {
	return file_file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterFileResponse) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *RegisterFileResponse) GetPutUrl() string {
	if x != nil {
		return x.PutUrl
	}
	return ""
}

// Выдать ссылку для скачивания по file_id
type DownloadLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId int32 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *DownloadLinkRequest) Reset() {
	*x = DownloadLinkRequest{}
	mi := &file_file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadLinkRequest) ProtoMessage() {}

func (x *DownloadLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadLinkRequest.ProtoReflect.Descriptor instead.
func (*DownloadLinkRequest) Descriptor() ([]byte, []int) {
	return file_file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadLinkRequest) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type DownloadLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // presigned GET
}

func (x *DownloadLinkResponse) Reset() {
	*x = DownloadLinkResponse{}
	mi := &file_file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadLinkResponse) ProtoMessage() {}

func (x *DownloadLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadLinkResponse.ProtoReflect.Descriptor instead.
func (*DownloadLinkResponse) Descriptor() ([]byte, []int) {
	return file_file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_file_storage_proto protoreflect.FileDescriptor

var file_file_storage_proto_rawDesc = []byte{
	0x0a, 0x12, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x75, 0x0a, 0x13, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x48, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x75, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x2e, 0x0a, 0x13,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x14,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0xa6, 0x01, 0x0a, 0x12, 0x46, 0x69, 0x6c, 0x65, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a,
	0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_file_storage_proto_rawDescOnce sync.Once
	file_file_storage_proto_rawDescData = file_file_storage_proto_rawDesc
)

func file_file_storage_proto_rawDescGZIP() []byte {
	file_file_storage_proto_rawDescOnce.Do(func() {
		file_file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_storage_proto_rawDescData)
	})
	return file_file_storage_proto_rawDescData
}

var file_file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_storage_proto_goTypes = []any{
	(*RegisterFileRequest)(nil),  // 0: files.RegisterFileRequest
	(*RegisterFileResponse)(nil), // 1: files.RegisterFileResponse
	(*DownloadLinkRequest)(nil),  // 2: files.DownloadLinkRequest
	(*DownloadLinkResponse)(nil), // 3: files.DownloadLinkResponse
}
var file_file_storage_proto_depIdxs = []int32{
	0, // 0: files.FileStorageService.RegisterFile:input_type -> files.RegisterFileRequest
	2, // 1: files.FileStorageService.DownloadLink:input_type -> files.DownloadLinkRequest
	1, // 2: files.FileStorageService.RegisterFile:output_type -> files.RegisterFileResponse
	3, // 3: files.FileStorageService.DownloadLink:output_type -> files.DownloadLinkResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_storage_proto_init() }
func file_file_storage_proto_init() {
	if File_file_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_storage_proto_goTypes,
		DependencyIndexes: file_file_storage_proto_depIdxs,
		MessageInfos:      file_file_storage_proto_msgTypes,
	}.Build()
	File_file_storage_proto = out.File
	file_file_storage_proto_rawDesc = nil
	file_file_storage_proto_goTypes = nil
	file_file_storage_proto_depIdxs = nil
}
